### ISSUE TITLE
Gebote erscheinen alle doppelt

### ISSUE THREAD

**Issue by ljonka** [sWalbrun/solawi#2]
Hallo! Nach der ersten Abstimmung kam der Fehler 500, bei einer erneuten Abstimmung / Korrektur erscheinen nun für jede Stufe (1-3) jeweils zwei Einträge.

Gruß

**Comment by sWalbrun** [comment]
Tritt der Fehler immer noch auf bzw. hast du da einen Screenshot?
Ich konnte die letzten Tage keine Einträge mehr in den Logs entdecken

**Comment by sWalbrun** [comment]
Der Fehler war ein Folgefehler. Die Datenbankstruktur war zum Zeitpunkt der ersten Abgabe veraltet und dann wurden wirklich 6 Gebote abgegeben. Die Struktur ist inzwischen aber gefixed
